// Shared property data for both listing and detail pages
export const allPropertiesData = [
  {
    id: 1,
    title: "3 BHK Flat for Sale in Sector 94, Noida Express Way, Noida",
    developer: "M3M The Cullinan",
    image: "/static/no_image.png",
    imageLabel: "Huge Swimming Pool",
    superArea: "3200 sqft",
    status: "Under Construction",
    possession: "Poss. by Apr '28",
    furnishing: "Unfurnished",
    bathroom: "4",
    transaction: "New Property",
    balcony: "5",
    description:
      "Multistorey Apartment for Sale in Sector 94, Noida. Covered area is 3200.0 Sq-ft. This property belongs to \"M3M The Cullinan\". This is a premium residential project offering world-class amenities and modern living spaces.",
    price: "7.04 Cr",
    pricePerSqft: "₹22,000 per sqft",
    photos: "39+",
    postedDate: "Oct 20, '25",
    buttonType: "phone",
    verified: true,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 2,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Golfshire",
    image: "/static/no_image.png",
    imageLabel: "39+ Photos",
    superArea: "2095 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2095.0 Sq-ft. This property offers spacious living with modern amenities and excellent connectivity.",
    price: "2.45 Cr",
    pricePerSqft: "₹11,716 per sqft",
    photos: "39+",
    postedDate: "Oct 20, '25",
    buttonType: "enquire",
    verified: false,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 3,
    title: "3 BHK Flat for Sale in Sector 152, Noida Express Way, Noida",
    developer: "ATS Picturesque Reprieves",
    image: "/static/no_image.png",
    imageLabel: "23+ Photos",
    superArea: "2350 sqft",
    status: "Ready to Move",
    transaction: "New Property",
    description:
      "Multistorey Apartment for Sale in Sector 152, Noida. Covered area is 2350.0 Sq-ft. This property is ready to move in with all modern amenities.",
    price: "2.82 Cr",
    pricePerSqft: "₹12,000 per sqft",
    photos: "23+",
    postedDate: "Yesterday",
    buttonType: "enquire",
    verified: true,
    seen: true,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 4,
    title: "2 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "1500 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 1500.0 Sq-ft. Perfect for small families looking for affordable housing.",
    price: "₹50 Lakh",
    pricePerSqft: "₹33,333 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: false,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 5,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers luxury living with premium amenities.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: true,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 12,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers modern living spaces.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: false,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 13,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers comfortable living.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: false,
    seen: true,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 7,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers premium living.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: true,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 8,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers modern amenities.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: false,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 9,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers spacious living.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: false,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 10,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers luxury amenities.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: true,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
  {
    id: 11,
    title: "3 BHK Flat for Sale in Sector 150, Pusta Road, Noida",
    developer: "ACE Parkway",
    image: "/static/no_image.png",
    imageLabel: "61+ Photos",
    superArea: "2190 sqft",
    transaction: "New Property",
    furnishing: "Unfurnished",
    description:
      "Multistorey Apartment for Sale in Sector 150, Noida. Covered area is 2190.0 Sq-ft. This property offers contemporary living.",
    price: "3.13 Cr",
    pricePerSqft: "₹14,300 per sqft",
    photos: "61+",
    postedDate: "Oct 21, '25",
    buttonType: "enquire",
    verified: false,
    seen: false,
    propertyTypeCategory: "Residential Apartment",
  },
];

// Helper function to get property by ID
export const getPropertyById = (id) => {
  return allPropertiesData.find((property) => property.id === parseInt(id));
};


